apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: {{ .Values.database.namespace }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: mongo
            args:
            - "/bin/sh"
            - "-c"
            - "/scripts/backup.sh"
            - "tar cvzf mongodb-backup.tar.gz /tmp/backup"
            #- gsutil cp mongodb-backup.tar.gz gs://my-project/backups/mongodb-backup.tar.gz
            envFrom:
            - secretRef:
                name: mongodb-secret
            volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
            volumeMounts:
            - name: backup-script
              mountPath: /scripts/backup.sh
              subPath: backup.sh
          restartPolicy: OnFailure
          volumes:
          - name: mongodb-persistent-storage
            persistentVolumeClaim:
              claimName: mongodb-pv-claim
          volumes:
          - name: backup-script
            configMap:
              name: mongodb-config-file
              defaultMode: 0777
