apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.database.namespace }}
data:
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.database.rootPassword | b64enc }}
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.database.rootUsername }}
