apiVersion: v1
data:
  mongodb.conf: |+
    systemLog:
       destination: file
       path: "/var/log/mongodb/mongod.log"
       logAppend: true
    storage:
       journal:
          enabled: true
    processManagement:
       fork: true
    net:
       bindIp: 127.0.0.1
       port: 27017
    setParameter:
       enableLocalhostAuthBypass: false
  backup.sh: |
    #!/bin/bash
    /usr/bin/mongodump -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD -o /tmp/backup -h {{ .Values.application.name }}

kind: ConfigMap
metadata:
  name: mongodb-config-file
  namespace: {{ .Values.database.namespace }}
