apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.database.namespace }}
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: {{ .Values.application.name }}
  type: NodePort
status:
  loadBalancer: {}
