apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongo-helmchart.deployment" . }}
  namespace: {{ .Values.database.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mongo-helmchart.deployment" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongo-helmchart.deployment" . }}
    spec:
      containers:
      - name: {{ include "mongo-helmchart.deployment" . }}
        image: mongo
        startupProbe:
          httpGet:
            path: /health/startup
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          successThreshold: 3
        ports:
          - containerPort: 27017
        envFrom:
        - secretRef:
            name: mongodb-secret
        volumeMounts:
        - name: mongodb-configuration-file
          mountPath: /etc/mongod.conf
          readOnly: true
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
      - name: mongodb-configuration-file
        configMap:
          name: mongodb-config-file
