name: release
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published, created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish Helm charts
        uses: J12934/helm-gh-pages-action@master
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: "./"
